### ISSUE TITLE
Go-Live Smoke Testing: Fire Landing Page

### ISSUE THREAD

**Issue by sarah0arnold** [aemsites/clarkcountynv#1305]
Page: https://www.clarkcountynv.gov/government/departments/fire/

Issues: 
1. Sub menu does not open on mobile or in mobile inspect mode
2. 2nd, 3rd and 4th images are not appearing in slider

**Comment by smrutimohapatra87** [comment]
@sarah0arnold : This is fixed

**Comment by sarah0arnold** [comment]
@akasjain2 we tested this on our triage call and the submenu is still not opening, please reopen the ticket and resolve
