### ISSUE TITLE
UAT 2 Levels of drill down in document search

### ISSUE THREAD

**Issue by sarah0arnold** [aemsites/clarkcountynv#581]
Page: 
https://main--clarkcountynv--aemsites.aem.live/government/elected_officials/county_treasurer/holdings-reports

**Comment by sarah0arnold** [comment]
Also: 
https://main--clarkcountynv--aemsites.aem.live/government/elected_officials/county_treasurer/monthly-reports

**Comment by sarah0arnold** [comment]
Also: https://main--clarkcountynv--aemsites.aem.live/government/departments/building___fire_prevention/statistics-service-goals

Or discuss with Patrick approval for approach and communication plan to department affected.

**Comment by akasjain2** [comment]
Fixed via #877

**Comment by sarah0arnold** [comment]
Content not resolved yet

**Comment by sarah0arnold** [comment]
@akasjain2 can we reimport these pages that have accordion within accordion because the issue is resolved, but the content is still not displaying in that 2 level view. This goes for all page types like this

**Comment by akasjain2** [comment]
@sarah0arnold : I will reimport all pages having dropdown inside the accordion and let you know. Thanks.

**Comment by akasjain2** [comment]
@sarah0arnold : All pages having dropdown inside accordion are fixed and reimported.
