### ISSUE TITLE
UAT Accordion within Accordion

### ISSUE THREAD

**Issue by sarah0arnold** [aemsites/clarkcountynv#705]
https://main--clarkcountynv--aemsites.aem.live/government/departments/building___fire_prevention/plan_submittal/additional-requirements

**Comment by sarah0arnold** [comment]
Also this page: https://main--clarkcountynv--aemsites.aem.page/government/departments/geographic_info_systems/services/free-gis-maps1

**Comment by akasjain2** [comment]
Fixed via https://github.com/aemsites/clarkcountynv/issues/877

**Comment by sarah0arnold** [comment]
@akasjain2 this page is not resolved, the table is still not appearing with the 'accordion within an accordion' type display
